# FROM node:16-alpine3.14 as build-env
# WORKDIR /app

# COPY ./package.json ./package-lock.json ./

# RUN npm ci --force

# COPY . ./

# RUN ls -al
# RUN npm run build:ssr

FROM node:16-alpine3.14

WORKDIR /app
# RUN mkdir -p /dist

# Copy dependency definitions
# COPY --from=build-env /app/dist dist
COPY /node/dist ./

# Expose the port the app runs in
EXPOSE 3000

# Serve the app
CMD ["node", "server.js"]
