name: trigger jenkins job

# or add https://jenkins.mohamed-mourabit.com/github-webhook
on:
  push:
    branches: [master]

env:
  JOB_NAME: 'tourisme'
  TOKEN: '114fc0d1d864b6fee4a850875f801152d1'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.mohamed-mourabit.com"
        user: "admin"
        token: ${{ env.TOKEN }}
        job: "${{ env.JOB_NAME }}"
